### ISSUE TITLE
Removing using namespace juce

### ISSUE THREAD

**Issue by FigBug** [MNSignalProcessing/BarelyML#2]
https://github.com/MNSignalProcessing/BarelyML/blob/1ad96f815542e44b6f11445ee044aaf7a1bfe6b8/BarelyML.h#L110

This will force anybody that uses your module to pull all of juce into global namespace

**Comment by MNSignalProcessing** [comment]
Good point. Will fix this.

**Comment by MNSignalProcessing** [comment]
I've removed the juce namespace from the header in v0.2. Please let me know if you find any other issues like this.

**Comment by FigBug** [comment]
Thanks
